---
- name: Create Lightspeed chatbot configuration secret
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Ensure required variables are defined
      ansible.builtin.assert:
        that:
          - aap_namespace is defined
          - secret_name is defined
          - chatbot_model is defined
          - chatbot_url is defined
          - chatbot_token is defined
          - chatbot_llm_provider_type is defined
        fail_msg: "Required variables are missing. Please check your extra vars file."

  tasks:

    - name: Create namespace if missing
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ aap_namespace }}"

    - name: Create chatbot configuration secret
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secret_name }}"
            namespace: "{{ aap_namespace }}"
          type: Opaque
          stringData:
            chatbot_model: "{{ chatbot_model }}"
            chatbot_url: "{{ chatbot_url }}"
            chatbot_token: "{{ chatbot_token }}"
            chatbot_llm_provider_type: "{{ chatbot_llm_provider_type }}"

    - name: Display next steps
      ansible.builtin.debug:
        msg:
          - "Chatbot configuration secret '{{ secret_name }}' created successfully in namespace '{{ aap_namespace }}'."
          - ""
          - "Configuration details:"
          - "  Model: {{ chatbot_model }}"
          - "  URL: {{ chatbot_url }}"
          - "  Token: {{ chatbot_token[:50] }}..."
          - ""
          - "Next steps:"
          - "1. Update your AAP CR to include:"
          - "   spec:"
          - "     lightspeed:"
          - "       disabled: false"
          - "       chatbot_config_secret_name: {{ secret_name }}"
          - ""
          - "2. Verify pods are running:"
          - "   - {{ aap_cr_name }}-lightspeed-api-<version>"
          - "   - {{ aap_cr_name }}-lightspeed-chatbot-api-<version>"
