---
- name: Reset AAP operator images to stock
  hosts: localhost
  gather_facts: false
  vars:
    aap_version: "2.6"
  pre_tasks:
    - name: Set namespace
      ansible.builtin.set_fact:
        _aap_namespace: "{{ aap_namespace | default('aap' ~ (aap_version | replace('.', ''))) }}"
  roles:
    - reset_operator_images
