---
- name: Reset AAP operator images to stock
  hosts: localhost
  gather_facts: false
  vars:
    aap_version: "2.6"

    # Mapping of operators to their deployment and container info
    _operator_mappings:
      - name: gateway
        deployment: aap-gateway-operator-controller-manager
        container: manager
      - name: controller
        deployment: automation-controller-operator-controller-manager
        container: automation-controller-manager
      - name: hub
        deployment: automation-hub-operator-controller-manager
        container: automation-hub-operator
      - name: eda
        deployment: eda-server-operator-controller-manager
        container: eda-manager
      - name: lightspeed
        deployment: ansible-lightspeed-operator-controller-manager
        container: ansible-lightspeed-manager
      - name: resource
        deployment: resource-operator-controller-manager
        container: platform-resource-manager

  pre_tasks:
    - name: Set namespace
      ansible.builtin.set_fact:
        _aap_namespace: "{{ aap_namespace | default('aap' ~ (aap_version | replace('.', ''))) }}"

    - name: Get saved original data from ConfigMap
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        api_version: v1
        kind: ConfigMap
        name: operator-image-overrides
        namespace: "{{ _aap_namespace }}"
      register: configmap_info

    - name: Fail if ConfigMap not found
      ansible.builtin.fail:
        msg: "ConfigMap 'operator-image-overrides' not found in namespace {{ _aap_namespace }}. No overrides to reset."
      when: configmap_info.resources | length == 0

    - name: Parse original data
      ansible.builtin.set_fact:
        _original_data: "{{ configmap_info.resources[0].data.overrides | from_json }}"

    - name: Build list of operators to reset
      ansible.builtin.set_fact:
        _resets: "{{ _operator_mappings | selectattr('name', 'in', _original_data.keys() | list) | list }}"

    - name: Display reset plan
      ansible.builtin.debug:
        msg:
          - "Namespace: {{ _aap_namespace }}"
          - "Operators to reset: {{ _resets | map(attribute='name') | list }}"

  tasks:
    - name: Patch deployment with original image
      loop: "{{ _resets }}"
      loop_control:
        label: "{{ item.name }}"
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        state: present
        api_version: apps/v1
        kind: Deployment
        name: "{{ item.deployment }}"
        namespace: "{{ _aap_namespace }}"
        definition:
          spec:
            template:
              spec:
                containers:
                  - name: "{{ item.container }}"
                    image: "{{ _original_data[item.name].image }}"
        merge_type: strategic-merge

    - name: Restore ownerReferences (re-attach to OLM)
      loop: "{{ _resets }}"
      loop_control:
        label: "{{ item.name }}"
      when: _original_data[item.name].ownerReferences | length > 0
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        state: present
        api_version: apps/v1
        kind: Deployment
        name: "{{ item.deployment }}"
        namespace: "{{ _aap_namespace }}"
        definition:
          metadata:
            ownerReferences: "{{ _original_data[item.name].ownerReferences }}"
        merge_type: strategic-merge

    - name: Wait for deployments to be ready
      loop: "{{ _resets }}"
      loop_control:
        label: "{{ item.name }}"
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        api_version: apps/v1
        kind: Deployment
        name: "{{ item.deployment }}"
        namespace: "{{ _aap_namespace }}"
      register: deploy_status
      until:
        - deploy_status.resources | length > 0
        - deploy_status.resources[0].status.readyReplicas is defined
        - deploy_status.resources[0].status.readyReplicas == deploy_status.resources[0].status.replicas
      retries: 30
      delay: 5

    - name: Delete ConfigMap
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        state: absent
        api_version: v1
        kind: ConfigMap
        name: operator-image-overrides
        namespace: "{{ _aap_namespace }}"

    - name: Display success
      ansible.builtin.debug:
        msg:
          - "Operator images reset to stock successfully"
          - "Operators reset: {{ _resets | map(attribute='name') | list }}"
          - "ownerReferences restored (deployments re-attached to OLM)"
