---
- name: Test Lightspeed chatbot configuration
  hosts: localhost
  gather_facts: false
  vars:
    test_prompt: "Say hello in exactly one word."

  pre_tasks:
    - name: Ensure required variables are defined
      ansible.builtin.assert:
        that:
          - chatbot_model is defined
          - chatbot_url is defined
          - chatbot_token is defined
          - chatbot_llm_provider_type is defined
        fail_msg: "Required variables are missing. Use -e @chatbot-vars.yml or provide them as extra vars."

  tasks:
    - name: Build API endpoint URL
      ansible.builtin.set_fact:
        api_endpoint: "{{ chatbot_url | regex_replace('/$', '') }}/chat/completions"
        api_version_param: "{{ '?api-version=2024-02-15-preview' if chatbot_llm_provider_type == 'azure_openai' else '' }}"

    - name: Display test configuration
      ansible.builtin.debug:
        msg:
          - "Testing chatbot configuration..."
          - "  Provider: {{ chatbot_llm_provider_type }}"
          - "  URL: {{ chatbot_url }}"
          - "  Model: {{ chatbot_model }}"
          - "  Endpoint: {{ api_endpoint }}{{ api_version_param }}"

    - name: Test API credentials (OpenAI/vLLM)
      when: chatbot_llm_provider_type in ['openai', 'rhoai_vllm']
      block:
        - name: Make API request
          ansible.builtin.uri:
            url: "{{ api_endpoint }}"
            method: POST
            headers:
              Content-Type: application/json
              Authorization: "Bearer {{ chatbot_token }}"
            body_format: json
            body:
              model: "{{ chatbot_model }}"
              messages:
                - role: user
                  content: "{{ test_prompt }}"
              max_completion_tokens: 10
            status_code: 200
            timeout: 30
          register: api_response

        - name: Display success message
          ansible.builtin.debug:
            msg:
              - "SUCCESS! API credentials are valid."
              - "Response: {{ api_response.json.choices[0].message.content }}"

    - name: Test API credentials (Azure OpenAI)
      when: chatbot_llm_provider_type == 'azure_openai'
      block:
        - name: Make API request
          ansible.builtin.uri:
            url: "{{ api_endpoint }}{{ api_version_param }}"
            method: POST
            headers:
              Content-Type: application/json
              api-key: "{{ chatbot_token }}"
            body_format: json
            body:
              model: "{{ chatbot_model }}"
              messages:
                - role: user
                  content: "{{ test_prompt }}"
              max_completion_tokens: 10
            status_code: 200
            timeout: 30
          register: api_response

        - name: Display success message
          ansible.builtin.debug:
            msg:
              - "SUCCESS! API credentials are valid."
              - "Response: {{ api_response.json.choices[0].message.content }}"
